---
- name: Add epel-release repo
  command: amazon-linux-extras install -y epel
  become: true

#Add epel-release repo for CentOS
- name: Add epel-release repo
  yum:
    name: epel-release
    state: present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red HatEnterprise Linux'


- name: Install prereq
  yum:
    name:
      - docker-compose
      - gcc
      - git
      - java
      - jq
      - libffi-devel
      - libxml2-devel
      - md5deep
      - net-tools
      - openssl
      - python-setuptools
      - python36
      - python36-pip
      - python36-setuptools
      - wget
      - yum-utils
    state: present

- name: Checks if the environment file already has an entry for the PATH
  replace:
    dest: /etc/environment
    regexp: 'PATH=(.*)'
    replace: 'PATH=\1'
  register: checkIfPATHIsHere

- name: Add a PATH entry with /usr/local/bin/ if the PATH is not already defined
  lineinfile:
    dest: /etc/environment
    state: present
    line: 'PATH=/usr/local/bin/:/usr/bin/'
    regexp: ''
    insertafter: EOF
  when: checkIfPATHIsHere.changed == false

- name: add  /usr/local/bin/ and /usr/bin/ to the PATH 
  lineinfile:
    dest: /etc/environment
    state: present
    backrefs: no
    regexp: 'PATH=(["])((?!.?/usr/local/bin/:/usr/bin/).?)(["])$'
    line: 'PATH=\1\2:/usr/local/bin/:/usr/bin/\3'
  when: checkIfPATHIsHere.changed